/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco;

import java.awt.Color;
import java.awt.Image;
import java.util.List;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUMNO
 */
public class SULY extends javax.swing.JFrame {

    Cliente[] clientes = new Cliente[20];
    String[] tiposDeCuenta = new String[20];
    int contadorClientes = 0;
    int contadorTyposDeCuenta = 0;

    public SULY() {
        initComponents();
        this.setSize(1025, 880);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        jPanel1.setBackground(Color.white);
        jPanel2.setBackground(Color.white);
        jPanel3.setBackground(Color.white);
        jPanel4.setBackground(Color.white);
        Image logo = getToolkit().getDefaultToolkit().getImage(getClass().getResource("/img/lsuly.jpg"));
        lblLogo.setIcon(new ImageIcon(logo.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH)));

        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/sulyss.jpg"));
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarcl = new javax.swing.JButton();
        txtclTelefono = new javax.swing.JTextField();
        txtclNombre = new javax.swing.JTextField();
        txtclDirec = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboClientecn = new javax.swing.JComboBox<>();
        cboTPcn = new javax.swing.JComboBox<>();
        btnMascn = new javax.swing.JButton();
        btnAgregarcn = new javax.swing.JButton();
        txtMontocn = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboClientemv = new javax.swing.JComboBox<>();
        cboCuentamv = new javax.swing.JComboBox<>();
        cboTPmv = new javax.swing.JComboBox<>();
        btnAgregarmv = new javax.swing.JButton();
        txtMontomv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboClientecc = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cboCuentacc = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANCO SULY");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setText("TELEFONO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setText("DIRECCION");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        btnAgregarcl.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnAgregarcl.setText("AGREGAR");
        btnAgregarcl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAgregarcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarclActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 40));

        txtclTelefono.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtclTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtclTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, 30));

        txtclNombre.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtclNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtclNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtclNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, 30));

        txtclDirec.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtclDirec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtclDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, 280));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setText("TIPO DE CUENTA");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("MONTO INCIAL");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel9.setText("CLIENTE");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        cboClientecn.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cboClientecn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(cboClientecn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, 30));

        cboTPcn.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cboTPcn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(cboTPcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, 30));

        btnMascn.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnMascn.setText("+");
        btnMascn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMascn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMascnActionPerformed(evt);
            }
        });
        jPanel2.add(btnMascn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 30, 30));

        btnAgregarcn.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnAgregarcn.setText("AGREGAR");
        btnAgregarcn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAgregarcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarcnActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 100, 40));

        txtMontocn.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtMontocn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMontocn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontocnActionPerformed(evt);
            }
        });
        jPanel2.add(txtMontocn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 320, 280));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimiento"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel8.setText("CLIENTE");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel10.setText("TIPO MOVIMIENTO");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, 30));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel11.setText("MONTO");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 30));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel12.setText("CUENTA");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 30));

        cboClientemv.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cboClientemv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(cboClientemv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 80, 30));

        cboCuentamv.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cboCuentamv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(cboCuentamv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 80, 30));

        cboTPmv.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cboTPmv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(cboTPmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 70, 30));

        btnAgregarmv.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnAgregarmv.setText("AGREGAR");
        jPanel3.add(btnAgregarmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 120, 40));

        txtMontomv.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtMontomv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtMontomv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 110, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 310, 290));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel13.setText("CONSULTAR CUENTA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 20));

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setText("Cliente");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 60, 30));

        cboClientecc.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cboClientecc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cboClientecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 140, 30));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setText("Cuenta");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 70, 30));

        cboCuentacc.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cboCuentacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboCuentacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCuentaccActionPerformed(evt);
            }
        });
        getContentPane().add(cboCuentacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 140, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel16.setText("TELEFONO");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel17.setText("DIRECCION");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel18.setText("TIPO CUENTA");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel19.setText("MONTO INICIAL");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel20.setText("NOMBRE");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 250, 20));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, 20));

        jLabel23.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 250, 20));

        jLabel24.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 250, 20));

        jLabel25.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 250, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 450, 260));

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMovimientos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 490, 160));

        jLabel21.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel21.setText("MOVIMIENTOS");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 120, 20));

        jLabel22.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel22.setText("SALDO");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 730, 100, 20));

        lblLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 710, 150));

        lblSaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 720, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontocnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontocnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontocnActionPerformed

    private void txtclNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclNombreActionPerformed

    }//GEN-LAST:event_txtclNombreActionPerformed

    private void btnAgregarclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarclActionPerformed

        String nombre = txtclNombre.getText();
        String telefono = txtclTelefono.getText();
        String direccion = txtclDirec.getText();
        Cliente newCliente = new Cliente(contadorClientes, nombre, telefono, direccion);
        clientes[contadorClientes++] = newCliente;
        List<String> clientesnombre = new ArrayList<String>();
        for (int i = 0; i < contadorClientes; i++) {
            clientesnombre.add(clientes[i].getNombre());
        }
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(clientesnombre.toArray());
        cboClientecn.setModel(comboModel);
        cboClientemv.setModel(comboModel);
        cboClientecc.setModel(comboModel);
    }//GEN-LAST:event_btnAgregarclActionPerformed

    private void btnMascnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMascnActionPerformed
        String acounttype = JOptionPane.showInputDialog(null, "INGRESA EL TIPO DE CUENTA");
        tiposDeCuenta[contadorTyposDeCuenta++] = acounttype;

        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(tiposDeCuenta);
        cboTPcn.setModel(comboModel);
    }//GEN-LAST:event_btnMascnActionPerformed

    private void btnAgregarcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarcnActionPerformed
        String cliente = (String) cboClientecn.getSelectedItem();
        String tipoCuentaSeleccionado = (String) cboTPcn.getSelectedItem();
        String montoInicial = txtMontocn.getText();
        String fecha = new Date().toString();
        Cliente tmp = null;
        int indexCliente = 0;
        for (int i = 0; i < contadorClientes; i++) {
            if (clientes[i].getNombre() == cliente) {
                tmp = clientes[i];
                indexCliente = i;
            }
        }
        Cuenta nuevaCuenta = new Cuenta(tmp.getCuentas().length, tipoCuentaSeleccionado, fecha, Double.parseDouble(montoInicial));
        tmp.addCuenta(nuevaCuenta);
        clientes[indexCliente] = tmp;
    }//GEN-LAST:event_btnAgregarcnActionPerformed

    private void cboCuentaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCuentaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCuentaccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SULY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SULY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SULY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SULY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SULY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarcl;
    private javax.swing.JButton btnAgregarcn;
    private javax.swing.JButton btnAgregarmv;
    private javax.swing.JButton btnMascn;
    private javax.swing.JComboBox<String> cboClientecc;
    private javax.swing.JComboBox<String> cboClientecn;
    private javax.swing.JComboBox<String> cboClientemv;
    private javax.swing.JComboBox<String> cboCuentacc;
    private javax.swing.JComboBox<String> cboCuentamv;
    private javax.swing.JComboBox<String> cboTPcn;
    private javax.swing.JComboBox<String> cboTPmv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtMontocn;
    private javax.swing.JTextField txtMontomv;
    private javax.swing.JTextField txtclDirec;
    private javax.swing.JTextField txtclNombre;
    private javax.swing.JTextField txtclTelefono;
    // End of variables declaration//GEN-END:variables
}
